### ISSUE TITLE
Parse error Joomla 3.7.0

### ISSUE THREAD

**Issue by annia316** [rvalitov/widgetkit-slideshow-ex#7]
I get following Error after installing the Sildeshow-ex Widget on my joomla site:

Parse error: syntax error, unexpected '[' in /usr/local/pem/vhosts/xxx/webspace/httpdocs/xxx/joomla/administrator/components/com_widgetkit/plugins/widgets/slideshow_ex/views/WidgetkitExPlugin.php on line 355

PHP Version 5.3.29

Removing the Slideshow_ex Folder solved the problem.

**Comment by rvalitov** [comment]
Thank you for reporting this. Probably it's because your PHP version it too old. Actually I didn't test this widget myself on such outdated version of PHP (I don't have PHP 5.3.x anywhere, so I can't test this case). I tested the widget with Joomla 3.7 with PHP 5.6 & PHP 7.0. I attach a patched version of the WidgetkitExPlugin.php file. Please, [download](https://mega.nz/#!uh13EbzT!NijNClBKP4_k-glrR7th9_3bARD6ktXvqUS_o7vDzTU) it, then replace the old version of this file on your server with the new one. After that please inform me if it will solve your problem. However, I suggest you to update to a newer version of PHP, at least 5.6.x or 7.0.x if possible.

**Comment by annia316** [comment]
Thank you very much for your effort! I am trying to talk my customer into updating the PHP version... you are totally right. Just wanted to let you know that this bug exists. I am going to test your patch and let you know.

**Comment by rvalitov** [comment]
@annia316 , please let me know if the patch solved your problem.

**Comment by annia316** [comment]
@rvalitov I get the same Parse error: syntax error, unexpected '[' in /.../administrator/components/com_widgetkit/plugins/widgets/slideshow_ex/views/WidgetkitExPlugin.php on line 355

**Comment by rvalitov** [comment]
It seems I can't fix it without having access to your Joomla. Can you create administrative account to the Joomla backend and send the login credentials privately to me to ramilvalitov@gmail.com
Thank you!

**Comment by rvalitov** [comment]
@annia316 if my request is a problem, please let me know. I will try to find PHP 5.3 and setup a virtual machine for that.

**Comment by rvalitov** [comment]
I close this issue, because I don't get any reply from you.
